version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build_and_test:
    docker:
      - image: cimg/node:18.15.0-browsers
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn install
      - run: yarn lint
      - run: CI=true yarn test --verbose --ci --runInBand --coverage --passWithNoTests

  deploy:
    docker:
      - image: cimg/node:18.15.0-browsers
    steps:
      - checkout
      - run:
          name: Create .env file
          command: |
              touch .env;
              echo REACT_APP_FIREBASE_API_KEY=$REACT_APP_FIREBASE_API_KEY >> .env;
              echo REACT_APP_FIREBASE_AUTH_DOMAIN=$REACT_APP_FIREBASE_AUTH_DOMAIN >> .env;
              echo REACT_APP_FIREBASE_PROJECT_ID=$REACT_APP_FIREBASE_PROJECT_ID >> .env;
              echo REACT_APP_FIREBASE_STORAGE_BUCKET=$REACT_APP_FIREBASE_STORAGE_BUCKET >> .env;
              echo REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$REACT_APP_FIREBASE_MESSAGING_SENDER_ID >> .env;
              echo REACT_APP_FIREBASE_APP_ID=$REACT_APP_FIREBASE_APP_ID >> .env;
              echo REACT_APP_FIREBASE_MEASUREMENT_ID=$REACT_APP_FIREBASE_MEASUREMENT_ID >> .env;

      - run: yarn install
      - run:
          name: Deploy Firebase Hosting
          command: |
              case $CIRCLE_BRANCH in
                "master")
                    yarn deploy --token=$FIREBASE_TOKEN
                    ;;
                "production")
                    yarn deploy-prod --token=$FIREBASE_TOKEN
                    ;;
                esac

workflows:
  workflow:
    jobs:
      - build_and_test
      - deploy:
          context: project-name-dev
          requires:
            - build_and_test
          filters:
            branches:
              only: master
      - deploy:
          context: project-name-prod
          requires:
            - build_and_test
          filters:
            branches:
              only: production
